In [1]:
zeros(3, 3)

3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

In [2]:
ones(Int64, 7)

7-element Vector{Int64}:
 1
 1
 1
 1
 1
 1
 1

In [3]:
trues(2)

2-element BitVector:
 1
 1

In [4]:
[1,2.3]

2-element Vector{Float64}:
 1.0
 2.3

In [5]:
[1;2]

2-element Vector{Int64}:
 1
 2

In [6]:
[1 2]

1×2 Matrix{Int64}:
 1  2

In [7]:
[1 2;3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [9]:
[[1,2] [3,4]]

2×2 Matrix{Int64}:
 1  3
 2  4

In [20]:
[sin(pi*x/4) for x ∈ range(0,10,11)]

11-element Vector{Float64}:
  0.0
  0.7071067811865475
  1.0
  0.7071067811865476
  1.2246467991473532e-16
 -0.7071067811865475
 -1.0
 -0.7071067811865477
 -2.4492935982947064e-16
  0.7071067811865474
  1.0

In [21]:
a = [1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [22]:
a[:,1]

3-element Vector{Int64}:
 1
 4
 7

In [23]:
a[2,:]

3-element Vector{Int64}:
 4
 5
 6

In [30]:
a[[1,3],:]

2×3 Matrix{Int64}:
 1  2  3
 7  8  9

In [32]:
a[:, [true,false,false]]

3×1 Matrix{Int64}:
 1
 4
 7

In [33]:
a[[1],:]

1×3 Matrix{Int64}:
 1  2  3

In [34]:
a[1,3]

3

In [35]:
a[1,:]

3-element Vector{Int64}:
 1
 2
 3

In [38]:
max.([1,3], [2,0])

2-element Vector{Int64}:
 2
 3

In [41]:
myAdd = (x,y) -> x + y

#17 (generic function with 1 method)

In [43]:
myAdd.( [1,3], [2,0] )

2-element Vector{Int64}:
 3
 3